
#
# MsgLab by zProgramm
# Version: 1.8.8
#

version: 1.9.1

config:

  # List of enabled commands and options:
  modules:
    enabled-commands:
      - chat
      - bmsg
      - msg
      - reply
      - socialspy
      - broadcast
      - broadcastworld
      - stream
      - ignore
      - unignore
      - helpop
      - staffchat
      - channel
      - motd

    enabled-options:
      - chat_format
      - chat_revisor
      - cooldown
      - join_quit
      - motd


perms:

  # Revisor:
  revisor:
    watch: bmsg.revisor
    bypass: bmsg.revisor

  # Cooldown:
  cooldown:
    chat-bypass: bmsg.chat.bypass
    cmd-bypass: bmsg.cmd.bypass

  # Commands:
  commands:
    bmsg:
      main: bmsg.commands.bmsg
      debug: bmsg.commands.bmsg.debug
      restore: bmsg.commands.bmsg.restore
      reload: bmsg.commands.bmsg.reload

    broadcast:
      main: bmsg.commands.broadcast
      click: bmsg.commands.broadcast.click

    broadcast-world:
      main: bmsg.commands.broadcast-world
      click: bmsg.commands.broadcast-world.click

    channel:
      main: bmsg.commands.channel
      move: bmsg.commands.move

    chat:
      main: bmsg.commands.chat
      reload: bmsg.commands.chat.reload

    helpop:
      main: bmsg.commands.helpop
      watch: bmsg.commands.helpop.watch

    ignore: bmsg.commands.ignore

    motd:
      main: bmsg.commands.motd
      admin: bmsg.commands.motd.admin

    msg:
      main: bmsg.commands.msg
      toggle: bmsg.commands.msg.toggle

    reply:
      main: bmsg.commands.reply

    socialspy:
      main: bmsg.commands.socialspy

    staffchat:
      main: bmsg.commands.staffchat

    stream:
      main: bmsg.commands.stream

    unignore:
      main: bmsg.commands.unignore

  # Color:
  color:
    commands: bmsg.commands.color
    chat: bmsg.chat.color


# Options:
options:
  # You can create prefixes with variables unlimited, obiously!
  replacer:

    # Prefix config:
    prefix:
      format: "&a[Bmsg] &8|"
      variable: "%c"
    # Error config:
    error:
      format: "&c[Error] &8|"
      variable: "%e"

  metrics: true
  update-check: false
  # To allow hover.
  allow-hover: true
  hover-format: "{%format%}"

  # To allow hex color. [Only 1.16+]
  allow-hexcolor: true
  hexcolor-format: "#%hexcolor%"

  # If you allow the subcommand to go to the support of the plugin /bmsg support.
  allow-support: true